export const LOGIN_DEVICE_LOADING = "LOGIN_DEVICE_LOADING";
export const LOGIN_DEVICE_SUCCESS = "LOGIN_DEVICE_SUCCESS";
export const LOGIN_DEVICE_ERROR = "LOGIN_DEVICE_ERROR";
export const LOGOUT_DEVICE = "LOGOUT_DEVICE";

export const REGISTER_DEVICE_LOADING = "REGISTER_DEVICE_LOADING";
export const REGISTER_DEVICE_SUCCESS = "REGISTER_DEVICE_SUCCESS";
export const REGISTER_DEVICE_ERROR = "REGISTER_DEVICE_ERROR";
