export const LOGIN_DEVICE_LOADING = "LOGIN_DEVICE_LOADING";
export const LOGIN_DEVICE_SUCCESS = "LOGIN_DEVICE_SUCCESS";
export const LOGIN_DEVICE_ERROR = "LOGIN_DEVICE_ERROR";
export const LOGOUT_DEVICE = "LOGOUT_DEVICE";
