export const SEND_MESSAGE_LOADING = "SEND_MESSAGE_LOADING";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET";

export const GET_MESSAGE_LOADING = "GET_MESSAGE_LOADING";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_ERROR = "GET_MESSAGE_ERROR";
export const GET_MESSAGE_RESET = "GET_MESSAGE_RESET";

export const GET_MESSAGES_LOADING = "GET_MESSAGES_LOADING";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR";
export const GET_MESSAGES_RESET = "GET_MESSAGES_RESET";
